/**
 * @packageDocumentation
 * @module api.functional.internal
 */
//================================================================
import { AesPkcs5 } from "./../../__internal/AesPkcs5";
import { Fetcher } from "./../../__internal/Fetcher";
import { Primitive } from "./../../Primitive";
import type { IConnection } from "./../../IConnection";

import type { IPaymentWebhook } from "./../../structures/IPaymentWebhook";


/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller PaymentInternalController.webhook()
 * @path POST /internal/webhook
 */
export function webhook
    (
        connection: IConnection,
        input: Primitive<webhook.Input>
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        webhook.CONFIG,
        webhook.METHOD,
        webhook.path(),
        input
    );
}
export namespace webhook
{
    export type Input = Primitive<IPaymentWebhook>;


    export const METHOD = "POST";
    export const PATH = "/internal/webhook";
    export const CONFIG = {
        input_encrypted: true,
        output_encrypted: true,
    };

    export function path(): string
    {
        return `/internal/webhook`;
    }
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
