/**
 * @packageDocumentation
 * @module api.functional.webhooks
 */
//================================================================
import { AesPkcs5 } from "./../../__internal/AesPkcs5";
import { Fetcher } from "./../../__internal/Fetcher";
import { Primitive } from "./../../Primitive";
import type { IConnection } from "./../../IConnection";

import type { IIamportPayment } from "./../../../../node_modules/iamport-server-api/lib/structures/IIamportPayment";
import type { ITossPaymentWebhook } from "./../../../../node_modules/toss-payments-server-api/lib/structures/ITossPaymentWebhook";


/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller PaymentWebhooksController.iamport()
 * @path POST /webhooks/iamport
 */
export function iamport
    (
        connection: IConnection,
        input: Primitive<iamport.Input>
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        iamport.CONFIG,
        iamport.METHOD,
        iamport.path(),
        input
    );
}
export namespace iamport
{
    export type Input = Primitive<IIamportPayment.IWebhook>;


    export const METHOD = "POST";
    export const PATH = "/webhooks/iamport";
    export const CONFIG = {
        input_encrypted: false,
        output_encrypted: false,
    };

    export function path(): string
    {
        return `/webhooks/iamport`;
    }
}

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller PaymentWebhooksController.toss()
 * @path POST /webhooks/toss
 */
export function toss
    (
        connection: IConnection,
        input: Primitive<toss.Input>
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        toss.CONFIG,
        toss.METHOD,
        toss.path(),
        input
    );
}
export namespace toss
{
    export type Input = Primitive<ITossPaymentWebhook>;


    export const METHOD = "POST";
    export const PATH = "/webhooks/toss";
    export const CONFIG = {
        input_encrypted: false,
        output_encrypted: false,
    };

    export function path(): string
    {
        return `/webhooks/toss`;
    }
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
